name: Terraform Infra

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/terraform.yml'
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Auth GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set GCP Project
      run: gcloud config set project ${{ secrets.GCP_PROJECT }}

    - name: Terraform Init
      working-directory: infra
      run: terraform init

    - name: Terraform Apply
      working-directory: infra
      run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT }}"
